library(igraph)
library(igraphdata)
library(keyplayer)
library(gtools)
library(Matrix)

source("matrixToGraph.R")
source("threshold.R")
source("thresholdGreedy.R")
#source("thresholdGHeur1.R")
#source("thresholdGHeur3.R")
source("thresholdGreedyStepwise.R")
#source("thresholdGSHeur1.R")
#source("thresholdGSHeur2.R")
#source("thresholdGSHeur3.R")
#source("randomNetworks.R")
#source("carga.R")

datafr <- read.table("amigos.txt", header = TRUE)
gFriends <- graph.data.frame(datafr, directed = TRUE)
datafr <- read.table("libros.txt", header = TRUE)
gBooks <- graph.data.frame(datafr, directed = TRUE)
datafr <- read.table("delfines.txt", header = TRUE)
gDolphins <- graph.data.frame(datafr, directed = TRUE)
data("UKfaculty")
madj <- (as_adjacency_matrix(UKfaculty, attr = "weight"))*6/100
gFaculty <- graph.adjacency(madj, mode = "directed", weighted = TRUE)


tgsb1 <- thresholdGreedyStepwise(gBooks, 8, loops = 1)
tgsb2 <- thresholdGreedyStepwise(gBooks, 8, loops = 2)
tgsb5 <- thresholdGreedyStepwise(gBooks, 8, loops = 5)
tgsb10 <- thresholdGreedyStepwise(gBooks, 8, loops = 10)
tgsb20 <- thresholdGreedyStepwise(gBooks, 8, loops = 20)
tgsb50 <- thresholdGreedyStepwise(gBooks, 8, loops = 50)
tgsb100 <- thresholdGreedyStepwise(gBooks, 8, loops = 100)
tgsb200 <- thresholdGreedyStepwise(gBooks, 8, loops = 200)
tgsb500 <- thresholdGreedyStepwise(gBooks, 8, loops = 500)
tgsb1000 <- thresholdGreedyStepwise(gBooks, 8, loops = 1000)
tgsb2000 <- thresholdGreedyStepwise(gBooks, 8, loops = 2000)
tgsb5000 <- thresholdGreedyStepwise(gBooks, 8, loops = 5000)
tgsb10000 <- thresholdGreedyStepwise(gBooks, 8, loops = 10000)

tgsd1 <- thresholdGreedyStepwise(gDolphins, 4, loops = 1)
tgsd2 <- thresholdGreedyStepwise(gDolphins, 4, loops = 2)
tgsd5 <- thresholdGreedyStepwise(gDolphins, 4, loops = 5)
tgsd10 <- thresholdGreedyStepwise(gDolphins, 4, loops = 10)
tgsd20 <- thresholdGreedyStepwise(gDolphins, 4, loops = 20)
tgsd50 <- thresholdGreedyStepwise(gDolphins, 4, loops = 50)
tgsd100 <- thresholdGreedyStepwise(gDolphins, 4, loops = 100)
tgsd200 <- thresholdGreedyStepwise(gDolphins, 4, loops = 200)
tgsd500 <- thresholdGreedyStepwise(gDolphins, 4, loops = 500)
tgsd1000 <- thresholdGreedyStepwise(gDolphins, 4, loops = 1000)
tgsd2000 <- thresholdGreedyStepwise(gDolphins, 4, loops = 2000)
tgsd5000 <- thresholdGreedyStepwise(gDolphins, 4, loops = 5000)
tgsd10000 <- thresholdGreedyStepwise(gDolphins, 4, loops = 10000)

tgsfa1 <- thresholdGreedyStepwise(gFaculty, 4, loops = 1)
tgsfa2 <- thresholdGreedyStepwise(gFaculty, 4, loops = 2)
tgsfa5 <- thresholdGreedyStepwise(gFaculty, 4, loops = 5)
tgsfa10 <- thresholdGreedyStepwise(gFaculty, 4, loops = 10)
tgsfa20 <- thresholdGreedyStepwise(gFaculty, 4, loops = 20)
tgsfa50 <- thresholdGreedyStepwise(gFaculty, 4, loops = 50)
tgsfa100 <- thresholdGreedyStepwise(gFaculty, 4, loops = 100)
tgsfa200 <- thresholdGreedyStepwise(gFaculty, 4, loops = 200)
tgsfa500 <- thresholdGreedyStepwise(gFaculty, 4, loops = 500)
tgsfa1000 <- thresholdGreedyStepwise(gFaculty, 4, loops = 1000)
tgsfa2000 <- thresholdGreedyStepwise(gFaculty, 4, loops = 2000)
tgsfa5000 <- thresholdGreedyStepwise(gFaculty, 4, loops = 5000)
tgsfa10000 <- thresholdGreedyStepwise(gFaculty, 4, loops = 10000)


#tgfri <- thresholdGreedy(gFriends, 10, loops = 100)
#tgsfri <- thresholdGreedyStepwise(gFriends, 10, loops = 100)
#tgsh1fri <- thresholdGSHeur1(gFriends, 10, loops = 100)
#tgh1fri <- thresholdGHeur1(gFriends, 10, loops = 100)
#tgs2fri <- thresholdGreedyStepwise(gFriends, 10, loops = 100)
#tgsh1fri2 <- thresholdGSHeur1(gFriends, 10, loops = 100)
#tgsh2fri <- thresholdGSHeur2(gFriends, 10, loops = 100, fixedGroup = 5)
#tgsh3fri <- thresholdGSHeur3(gFriends, 10, loops = 100, quantileHeur = 3)
#tgh3fri <- thresholdGHeur3(gFriends, 10, loops = 100, quantileHeur = 3)
#tgsh3fri2 <- thresholdGSHeur3(gFriends, 10, loops = 100, quantileHeur = 3)

#tgb <- thresholdGreedy(gBooks, 8, loops = 100)
#tgsb <- thresholdGreedyStepwise(gBooks, 8, loops = 100)
#tgsh1b <- thresholdGSHeur1(gBooks, 8, loops = 100)
#tgh1b <- thresholdGHeur1(gBooks, 8, loops = 100)
#tgs2b <- thresholdGreedyStepwise(gBooks, 8, loops = 100)
#tgsh1b2 <- thresholdGSHeur1(gBooks, 8, loops = 100)
#tgsh2b <- thresholdGSHeur2(gBooks, 8, loops = 100, fixedGroup = 4)
#tgsh3b <- thresholdGSHeur3(gBooks, 8, loops = 100, quantileHeur = 3)
#tgh3b <- thresholdGHeur3(gBooks, 8, loops = 100, quantileHeur = 3)
#tgsh3b2 <- thresholdGSHeur3(gBooks, 8, loops = 100, quantileHeur = 3)

#tgd <- thresholdGreedy(gDolphins, 4, loops = 100)
#tgsd <- thresholdGreedyStepwise(gDolphins, 4, loops = 100)
#tgsh1d <- thresholdGSHeur1(gDolphins, 4, loops = 100)
#tgh1d <- thresholdGHeur1(gDolphins, 4, loops = 100)
#tgs2d <- thresholdGreedyStepwise(gDolphins, 4, loops = 100)
#tgsh1d2 <- thresholdGSHeur1(gDolphins, 4, loops = 100)
#tgsh2d <- thresholdGSHeur2(gDolphins, 4, loops = 100, fixedGroup = 2)
#tgsh3d <- thresholdGSHeur3(gDolphins, 4, loops = 100, quantileHeur = 3)
#tgh3d <- thresholdGHeur3(gDolphins, 4, loops = 100, quantileHeur = 3)
#tgsh3d2 <- thresholdGSHeur3(gDolphins, 4, loops = 100, quantileHeur = 3)

#tgfa <- thresholdGreedy(gFaculty, 4, loops = 100)
#tgsfa <- thresholdGreedyStepwise(gFaculty, 4, loops = 100)
#tgsh1fa <- thresholdGSHeur1(gFaculty, 4, loops = 100)
#tgh1fa <- thresholdGHeur1(gFaculty, 4, loops = 100)
#tgs2fa <- thresholdGreedyStepwise(gFaculty, 4, loops = 100)
#tgsh1fa2 <- thresholdGSHeur1(gFaculty, 4, loops = 100)
#tgsh2fa <- thresholdGSHeur2(gFaculty, 4, loops = 100, fixedGroup = 2)
#tgsh3fa <- thresholdGSHeur3(gFaculty, 4, loops = 100, quantileHeur = 3)
#tgh3fa <- thresholdGHeur3(gFaculty, 4, loops = 100, quantileHeur = 3)
#tgsh3fa2 <- thresholdGSHeur3(gFaculty, 4, loops = 100, quantileHeur = 3)
